image:
  file: .docker/gitpod/Dockerfile

vscode:
  extensions:
    - leanprover.lean4

tasks:
  - name: Build Dependencies
    init: |
      cd ./widget
      NODE_OPTIONS='--max-old-space-size=4096'
      npm clean-install && npm run build
      cd ..
      lake build ProofWidgets
